### ISSUE TITLE
Crash when trying to read endpoints from calico live cluster

### ISSUE THREAD

**Issue by zivnevo** [IBM/network-config-analyzer#240]
Running `nca.py --connectivity calico --pod_list calico` I get:
```
Traceback (most recent call last):
  File "C:\nevo\projects\network-config-analyzer\network-config-analyzer\nca.py", line 278, in <module>
    sys.exit(nca_main())
  File "C:\nevo\projects\network-config-analyzer\network-config-analyzer\nca.py", line 270, in nca_main
    ret_val = run_args(args)
  File "C:\nevo\projects\network-config-analyzer\network-config-analyzer\nca.py", line 172, in run_args
    network_config = resources_handler.get_network_config(np_list, ns_list, pod_list, resource_list,
  File "C:\nevo\projects\network-config-analyzer\network-config-analyzer\ResourcesHandler.py", line 62, in get_network_config
    self._set_config_peer_container(ns_list, pod_list, resource_list, config_name, save_flag, resources_parser)
  File "C:\nevo\projects\network-config-analyzer\network-config-analyzer\ResourcesHandler.py", line 76, in _set_config_peer_container
    success, res_type = resources_parser.parse_lists_for_topology(ns_list, pod_list, resource_list)
  File "C:\nevo\projects\network-config-analyzer\network-config-analyzer\ResourcesHandler.py", line 171, in parse_lists_for_topology
    self._parse_resources_path(pod_resource, [ResourceType.Pods])
  File "C:\nevo\projects\network-config-analyzer\network-config-analyzer\ResourcesHandler.py", line 242, in _parse_resources_path
    self._handle_calico_inputs(resource_flags)
  File "C:\nevo\projects\network-config-analyzer\network-config-analyzer\ResourcesHandler.py", line 282, in _handle_calico_inputs
    self.pods_finder.load_peer_from_calico_resource()
  File "C:\nevo\projects\network-config-analyzer\network-config-analyzer\TopologyObjectsFinder.py", line 34, in load_peer_from_calico_resource
    self.add_eps_from_yaml(peer_code)
  File "C:\nevo\projects\network-config-analyzer\network-config-analyzer\TopologyObjectsFinder.py", line 59, in add_eps_from_yaml
    self.add_eps_from_yaml(endpoint, kind[:-4])
  File "C:\nevo\projects\network-config-analyzer\network-config-analyzer\TopologyObjectsFinder.py", line 65, in add_eps_from_yaml
    self._add_wep_from_yaml(yaml_obj)
  File "C:\nevo\projects\network-config-analyzer\network-config-analyzer\TopologyObjectsFinder.py", line 224, in _add_wep_from_yaml
    wep_namespace = self.namespaces_finder.get_or_update_namespace(metadata.get('namespace', 'default'))
AttributeError: 'NoneType' object has no attribute 'get_or_update_namespace'
```

**Comment by zivnevo** [comment]
This also happens when running `nca.py --connectivity --resource_list calico`

**Comment by zivnevo** [comment]
We probably need a calico-setup and tests in our `test-push` workflow

**Comment by zivnevo** [comment]
The bug is fixed. Improvements to testing will be handled in #247
